/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

var fibonacci = [0, 1];
var sequencia = 1;
var valorMaximo = 4000000;

// definir a sequencia Fibonacci
for (var i = 2; sequencia <= valorMaximo; i++) {
  sequencia = fibonacci[i - 1] + fibonacci[i - 2];
  if (sequencia > valorMaximo) {
    break;
  }
  fibonacci.push(sequencia);
}

//soma da sequencia Fibonacci
soma = 0;
for (var i = 0; i < fibonacci.length; i++) {
  if (fibonacci[i] % 2 == 0) {
    soma += fibonacci[i];
  }
}
console.log(fibonacci);
console.log(soma);
